[package]
name = "chlog-rs"
version = "0.1.0"
authors = ["Rafael Ferreira <rafaelsf@gmail.com>"]

[dependencies]
regex = "0.2.3"
chrono = "0.4"
clap = "2.29.0"
ansi_term = "0.10.2"
reqwest = "0.8.2"
serde_json = "1.0"
serde = "1.0.27"
serde_derive = "1.0"
